# Generated by Django 4.0.5 on 2022-06-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
