# Generated by Django 4.0.5 on 2022-06-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_employee_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='media',
            new_name='files',
        ),
    ]
